# Generated by Django 4.2.29 on 2026-04-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat_feu', models.CharField(default='Vert', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('longueur', models.FloatField()),
                ('capacite_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('markov_state', models.CharField(max_length=50)),
                ('capacity_usage', models.FloatField()),
                ('active_cars', models.IntegerField()),
                ('system_efficiency', models.FloatField()),
                ('spawn_rate', models.FloatField()),
            ],
        ),
    ]
