# Generated by Django 4.2.29 on 2026-04-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficstats',
            options={'ordering': ['-date_save']},
        ),
        migrations.RenameField(
            model_name='trafficstats',
            old_name='timestamp',
            new_name='date_save',
        ),
        migrations.AlterField(
            model_name='trafficstats',
            name='active_cars',
            field=models.IntegerField(verbose_name='Véhicules Actifs'),
        ),
        migrations.AlterField(
            model_name='trafficstats',
            name='capacity_usage',
            field=models.FloatField(verbose_name='Occupation %'),
        ),
        migrations.AlterField(
            model_name='trafficstats',
            name='markov_state',
            field=models.CharField(max_length=50, verbose_name='État Markov'),
        ),
        migrations.AlterField(
            model_name='trafficstats',
            name='spawn_rate',
            field=models.FloatField(verbose_name='Taux de Spawn'),
        ),
        migrations.AlterField(
            model_name='trafficstats',
            name='system_efficiency',
            field=models.FloatField(verbose_name='Efficacité %'),
        ),
    ]
